/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */

/* THIS FILE IS AUTOGENERATED BY BPFTOOL! */
#ifndef __EXAMPLE2_BPF_SKEL_H__
#define __EXAMPLE2_BPF_SKEL_H__

#include <errno.h>
#include <stdlib.h>
#include <bpf/libbpf.h>

struct example2_bpf {
	struct bpf_object_skeleton *skeleton;
	struct bpf_object *obj;
	struct {
		struct bpf_map *openat_count;
	} maps;
	struct {
		struct bpf_program *bpf_prog1;
	} progs;
	struct {
		struct bpf_link *bpf_prog1;
	} links;

#ifdef __cplusplus
	static inline struct example2_bpf *open(const struct bpf_object_open_opts *opts = nullptr);
	static inline struct example2_bpf *open_and_load();
	static inline int load(struct example2_bpf *skel);
	static inline int attach(struct example2_bpf *skel);
	static inline void detach(struct example2_bpf *skel);
	static inline void destroy(struct example2_bpf *skel);
	static inline const void *elf_bytes(size_t *sz);
#endif /* __cplusplus */
};

static void
example2_bpf__destroy(struct example2_bpf *obj)
{
	if (!obj)
		return;
	if (obj->skeleton)
		bpf_object__destroy_skeleton(obj->skeleton);
	free(obj);
}

static inline int
example2_bpf__create_skeleton(struct example2_bpf *obj);

static inline struct example2_bpf *
example2_bpf__open_opts(const struct bpf_object_open_opts *opts)
{
	struct example2_bpf *obj;
	int err;

	obj = (struct example2_bpf *)calloc(1, sizeof(*obj));
	if (!obj) {
		errno = ENOMEM;
		return NULL;
	}

	err = example2_bpf__create_skeleton(obj);
	if (err)
		goto err_out;

	err = bpf_object__open_skeleton(obj->skeleton, opts);
	if (err)
		goto err_out;

	return obj;
err_out:
	example2_bpf__destroy(obj);
	errno = -err;
	return NULL;
}

static inline struct example2_bpf *
example2_bpf__open(void)
{
	return example2_bpf__open_opts(NULL);
}

static inline int
example2_bpf__load(struct example2_bpf *obj)
{
	return bpf_object__load_skeleton(obj->skeleton);
}

static inline struct example2_bpf *
example2_bpf__open_and_load(void)
{
	struct example2_bpf *obj;
	int err;

	obj = example2_bpf__open();
	if (!obj)
		return NULL;
	err = example2_bpf__load(obj);
	if (err) {
		example2_bpf__destroy(obj);
		errno = -err;
		return NULL;
	}
	return obj;
}

static inline int
example2_bpf__attach(struct example2_bpf *obj)
{
	return bpf_object__attach_skeleton(obj->skeleton);
}

static inline void
example2_bpf__detach(struct example2_bpf *obj)
{
	bpf_object__detach_skeleton(obj->skeleton);
}

static inline const void *example2_bpf__elf_bytes(size_t *sz);

static inline int
example2_bpf__create_skeleton(struct example2_bpf *obj)
{
	struct bpf_object_skeleton *s;
	int err;

	s = (struct bpf_object_skeleton *)calloc(1, sizeof(*s));
	if (!s)	{
		err = -ENOMEM;
		goto err;
	}

	s->sz = sizeof(*s);
	s->name = "example2_bpf";
	s->obj = &obj->obj;

	/* maps */
	s->map_cnt = 1;
	s->map_skel_sz = sizeof(*s->maps);
	s->maps = (struct bpf_map_skeleton *)calloc(s->map_cnt, s->map_skel_sz);
	if (!s->maps) {
		err = -ENOMEM;
		goto err;
	}

	s->maps[0].name = "openat_count";
	s->maps[0].map = &obj->maps.openat_count;

	/* programs */
	s->prog_cnt = 1;
	s->prog_skel_sz = sizeof(*s->progs);
	s->progs = (struct bpf_prog_skeleton *)calloc(s->prog_cnt, s->prog_skel_sz);
	if (!s->progs) {
		err = -ENOMEM;
		goto err;
	}

	s->progs[0].name = "bpf_prog1";
	s->progs[0].prog = &obj->progs.bpf_prog1;
	s->progs[0].link = &obj->links.bpf_prog1;

	s->data = (void *)example2_bpf__elf_bytes(&s->data_sz);

	obj->skeleton = s;
	return 0;
err:
	bpf_object__destroy_skeleton(s);
	return err;
}

static inline const void *example2_bpf__elf_bytes(size_t *sz)
{
	*sz = 3304;
	return (const void *)"\
\x7f\x45\x4c\x46\x02\x01\x01\0\0\0\0\0\0\0\0\0\x01\0\xf7\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\xa8\x09\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\x40\0\x0d\0\
\x01\0\x85\0\0\0\x0e\0\0\0\x77\0\0\0\x20\0\0\0\x63\x0a\xfc\xff\0\0\0\0\xbf\xa2\
\0\0\0\0\0\0\x07\x02\0\0\xfc\xff\xff\xff\x18\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x85\0\0\0\x01\0\0\0\x15\0\x04\0\0\0\0\0\x79\x01\0\0\0\0\0\0\x07\x01\0\0\x01\0\
\0\0\x7b\x10\0\0\0\0\0\0\x05\0\x0a\0\0\0\0\0\xb7\x01\0\0\x01\0\0\0\x7b\x1a\xf0\
\xff\0\0\0\0\xbf\xa2\0\0\0\0\0\0\x07\x02\0\0\xfc\xff\xff\xff\xbf\xa3\0\0\0\0\0\
\0\x07\x03\0\0\xf0\xff\xff\xff\x18\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xb7\x04\0\0\
\0\0\0\0\x85\0\0\0\x02\0\0\0\xb7\0\0\0\0\0\0\0\x95\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x47\x50\x4c\0\x9f\xeb\x01\0\
\x18\0\0\0\0\0\0\0\xc8\x02\0\0\xc8\x02\0\0\x70\x02\0\0\0\0\0\0\0\0\0\x02\x03\0\
\0\0\x01\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\x01\0\0\0\0\0\0\0\x03\0\0\0\0\x02\0\
\0\0\x04\0\0\0\x01\0\0\0\x05\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\0\0\0\0\0\0\0\
\x02\x06\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x02\0\0\0\x04\0\0\0\0\x20\0\0\0\0\0\0\
\0\0\0\x02\x08\0\0\0\x19\0\0\0\0\0\0\x08\x09\0\0\0\x1d\0\0\0\0\0\0\x08\x0a\0\0\
\0\x23\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\0\0\0\0\0\0\0\x02\x0c\0\0\0\x30\0\0\
\0\0\0\0\x08\x0d\0\0\0\x34\0\0\0\0\0\0\x08\x0e\0\0\0\x3a\0\0\0\0\0\0\x01\x08\0\
\0\0\x40\0\0\0\0\0\0\0\x04\0\0\x04\x20\0\0\0\x4d\0\0\0\x01\0\0\0\0\0\0\0\x52\0\
\0\0\x05\0\0\0\x40\0\0\0\x5e\0\0\0\x07\0\0\0\x80\0\0\0\x62\0\0\0\x0b\0\0\0\xc0\
\0\0\0\x68\0\0\0\0\0\0\x0e\x0f\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\x02\x12\0\0\0\x75\
\0\0\0\x15\0\0\x04\xa8\0\0\0\x7d\0\0\0\x13\0\0\0\0\0\0\0\x81\0\0\0\x13\0\0\0\
\x40\0\0\0\x85\0\0\0\x13\0\0\0\x80\0\0\0\x89\0\0\0\x13\0\0\0\xc0\0\0\0\x8d\0\0\
\0\x13\0\0\0\0\x01\0\0\x90\0\0\0\x13\0\0\0\x40\x01\0\0\x93\0\0\0\x13\0\0\0\x80\
\x01\0\0\x97\0\0\0\x13\0\0\0\xc0\x01\0\0\x9b\0\0\0\x13\0\0\0\0\x02\0\0\x9e\0\0\
\0\x13\0\0\0\x40\x02\0\0\xa1\0\0\0\x13\0\0\0\x80\x02\0\0\xa4\0\0\0\x13\0\0\0\
\xc0\x02\0\0\xa7\0\0\0\x13\0\0\0\0\x03\0\0\xaa\0\0\0\x13\0\0\0\x40\x03\0\0\xad\
\0\0\0\x13\0\0\0\x80\x03\0\0\xb0\0\0\0\x13\0\0\0\xc0\x03\0\0\xb8\0\0\0\x13\0\0\
\0\0\x04\0\0\xbb\0\0\0\x13\0\0\0\x40\x04\0\0\xbe\0\0\0\x13\0\0\0\x80\x04\0\0\
\xc4\0\0\0\x13\0\0\0\xc0\x04\0\0\xc7\0\0\0\x13\0\0\0\0\x05\0\0\xca\0\0\0\0\0\0\
\x01\x08\0\0\0\x40\0\0\0\0\0\0\0\x01\0\0\x0d\x02\0\0\0\xd8\0\0\0\x11\0\0\0\xdc\
\0\0\0\x01\0\0\x0c\x14\0\0\0\x54\x02\0\0\0\0\0\x01\x01\0\0\0\x08\0\0\x01\0\0\0\
\0\0\0\0\x03\0\0\0\0\x16\0\0\0\x04\0\0\0\x04\0\0\0\x59\x02\0\0\0\0\0\x0e\x17\0\
\0\0\x01\0\0\0\x62\x02\0\0\x01\0\0\x0f\0\0\0\0\x10\0\0\0\0\0\0\0\x20\0\0\0\x68\
\x02\0\0\x01\0\0\x0f\0\0\0\0\x18\0\0\0\0\0\0\0\x04\0\0\0\0\x69\x6e\x74\0\x5f\
\x5f\x41\x52\x52\x41\x59\x5f\x53\x49\x5a\x45\x5f\x54\x59\x50\x45\x5f\x5f\0\x75\
\x33\x32\0\x5f\x5f\x75\x33\x32\0\x75\x6e\x73\x69\x67\x6e\x65\x64\x20\x69\x6e\
\x74\0\x75\x36\x34\0\x5f\x5f\x75\x36\x34\0\x75\x6e\x73\x69\x67\x6e\x65\x64\x20\
\x6c\x6f\x6e\x67\x20\x6c\x6f\x6e\x67\0\x74\x79\x70\x65\0\x6d\x61\x78\x5f\x65\
\x6e\x74\x72\x69\x65\x73\0\x6b\x65\x79\0\x76\x61\x6c\x75\x65\0\x6f\x70\x65\x6e\
\x61\x74\x5f\x63\x6f\x75\x6e\x74\0\x70\x74\x5f\x72\x65\x67\x73\0\x72\x31\x35\0\
\x72\x31\x34\0\x72\x31\x33\0\x72\x31\x32\0\x62\x70\0\x62\x78\0\x72\x31\x31\0\
\x72\x31\x30\0\x72\x39\0\x72\x38\0\x61\x78\0\x63\x78\0\x64\x78\0\x73\x69\0\x64\
\x69\0\x6f\x72\x69\x67\x5f\x61\x78\0\x69\x70\0\x63\x73\0\x66\x6c\x61\x67\x73\0\
\x73\x70\0\x73\x73\0\x75\x6e\x73\x69\x67\x6e\x65\x64\x20\x6c\x6f\x6e\x67\0\x63\
\x74\x78\0\x62\x70\x66\x5f\x70\x72\x6f\x67\x31\0\x6b\x70\x72\x6f\x62\x65\x2f\
\x5f\x5f\x78\x36\x34\x5f\x73\x79\x73\x5f\x65\x78\x65\x63\x76\x65\0\x2f\x68\x6f\
\x6d\x65\x2f\x62\x75\x69\x6c\x64\x2f\x50\x72\x6f\x6a\x65\x63\x74\x73\x2f\x65\
\x62\x70\x66\x2d\x62\x6f\x6f\x6b\x2d\x63\x6f\x64\x65\x2d\x65\x78\x61\x6d\x70\
\x6c\x65\x73\x2f\x63\x68\x30\x35\x2f\x6c\x69\x62\x62\x70\x66\x2d\x63\x2f\x65\
\x78\x61\x6d\x70\x6c\x65\x32\x2f\x65\x78\x61\x6d\x70\x6c\x65\x32\x2e\x62\x70\
\x66\x2e\x63\0\x09\x75\x33\x32\x20\x70\x69\x64\x20\x3d\x20\x62\x70\x66\x5f\x67\
\x65\x74\x5f\x63\x75\x72\x72\x65\x6e\x74\x5f\x70\x69\x64\x5f\x74\x67\x69\x64\
\x28\x29\x20\x3e\x3e\x20\x33\x32\x3b\0\x09\x75\x36\x34\x2a\x20\x63\x6f\x75\x6e\
\x74\x20\x3d\x20\x62\x70\x66\x5f\x6d\x61\x70\x5f\x6c\x6f\x6f\x6b\x75\x70\x5f\
\x65\x6c\x65\x6d\x28\x26\x6f\x70\x65\x6e\x61\x74\x5f\x63\x6f\x75\x6e\x74\x2c\
\x20\x26\x70\x69\x64\x29\x3b\0\x09\x69\x66\x20\x28\x63\x6f\x75\x6e\x74\x29\x20\
\x7b\0\xc2\xa0\xc2\xa0\xc2\xa0\xc2\xa0\x09\xc2\xa0\x20\xc2\xa0\x20\x28\x2a\x63\
\x6f\x75\x6e\x74\x29\x2b\x2b\x3b\0\xc2\xa0\xc2\xa0\xc2\xa0\xc2\xa0\x09\xc2\xa0\
\x20\xc2\xa0\x20\x75\x36\x34\x20\x76\x61\x6c\x20\x3d\x20\x31\x3b\0\xc2\xa0\xc2\
\xa0\xc2\xa0\xc2\xa0\xc2\xa0\xc2\xa0\xc2\xa0\xc2\xa0\xc2\xa0\xc2\xa0\x20\x62\
\x70\x66\x5f\x6d\x61\x70\x5f\x75\x70\x64\x61\x74\x65\x5f\x65\x6c\x65\x6d\x28\
\x26\x6f\x70\x65\x6e\x61\x74\x5f\x63\x6f\x75\x6e\x74\x2c\x20\x26\x70\x69\x64\
\x2c\x20\x26\x76\x61\x6c\x2c\x20\x42\x50\x46\x5f\x41\x4e\x59\x29\x3b\0\x09\x72\
\x65\x74\x75\x72\x6e\x20\x30\x3b\0\x63\x68\x61\x72\0\x5f\x6c\x69\x63\x65\x6e\
\x73\x65\0\x2e\x6d\x61\x70\x73\0\x6c\x69\x63\x65\x6e\x73\x65\0\x9f\xeb\x01\0\
\x20\0\0\0\0\0\0\0\x14\0\0\0\x14\0\0\0\xbc\0\0\0\xd0\0\0\0\0\0\0\0\x08\0\0\0\
\xe6\0\0\0\x01\0\0\0\0\0\0\0\x15\0\0\0\x10\0\0\0\xe6\0\0\0\x0b\0\0\0\0\0\0\0\
\xfe\0\0\0\x51\x01\0\0\x0c\x4c\0\0\x08\0\0\0\xfe\0\0\0\x51\x01\0\0\x27\x4c\0\0\
\x10\0\0\0\xfe\0\0\0\x51\x01\0\0\x06\x4c\0\0\x20\0\0\0\xfe\0\0\0\0\0\0\0\0\0\0\
\0\x28\0\0\0\xfe\0\0\0\x7e\x01\0\0\x0f\x58\0\0\x40\0\0\0\xfe\0\0\0\xb6\x01\0\0\
\x06\x5c\0\0\x48\0\0\0\xfe\0\0\0\xc4\x01\0\0\x18\x60\0\0\x70\0\0\0\xfe\0\0\0\
\xdf\x01\0\0\x14\x68\0\0\x80\0\0\0\xfe\0\0\0\0\0\0\0\0\0\0\0\x98\0\0\0\xfe\0\0\
\0\xfb\x01\0\0\x16\x70\0\0\xb8\0\0\0\xfe\0\0\0\x49\x02\0\0\x02\x78\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x03\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x7a\0\0\0\0\0\x03\0\x68\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x73\0\0\0\0\0\x03\0\xb8\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x81\0\0\0\x12\0\x03\0\0\
\0\0\0\0\0\0\0\xc8\0\0\0\0\0\0\0\x14\0\0\0\x11\0\x05\0\0\0\0\0\0\0\0\0\x20\0\0\
\0\0\0\0\0\x51\0\0\0\x11\0\x06\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\x28\0\0\0\0\
\0\0\0\x01\0\0\0\x05\0\0\0\x98\0\0\0\0\0\0\0\x01\0\0\0\x05\0\0\0\xc0\x02\0\0\0\
\0\0\0\x04\0\0\0\x05\0\0\0\xd8\x02\0\0\0\0\0\0\x04\0\0\0\x06\0\0\0\x2c\0\0\0\0\
\0\0\0\x04\0\0\0\x01\0\0\0\x40\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x50\0\0\0\0\0\
\0\0\x04\0\0\0\x01\0\0\0\x60\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x70\0\0\0\0\0\0\
\0\x04\0\0\0\x01\0\0\0\x80\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x90\0\0\0\0\0\0\0\
\x04\0\0\0\x01\0\0\0\xa0\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\xb0\0\0\0\0\0\0\0\
\x04\0\0\0\x01\0\0\0\xc0\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\xd0\0\0\0\0\0\0\0\
\x04\0\0\0\x01\0\0\0\xe0\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x0d\x0e\x0f\0\x2e\
\x74\x65\x78\x74\0\x2e\x72\x65\x6c\x2e\x42\x54\x46\x2e\x65\x78\x74\0\x6f\x70\
\x65\x6e\x61\x74\x5f\x63\x6f\x75\x6e\x74\0\x2e\x6d\x61\x70\x73\0\x2e\x6c\x6c\
\x76\x6d\x5f\x61\x64\x64\x72\x73\x69\x67\0\x2e\x72\x65\x6c\x6b\x70\x72\x6f\x62\
\x65\x2f\x5f\x5f\x78\x36\x34\x5f\x73\x79\x73\x5f\x65\x78\x65\x63\x76\x65\0\x5f\
\x6c\x69\x63\x65\x6e\x73\x65\0\x2e\x73\x74\x72\x74\x61\x62\0\x2e\x73\x79\x6d\
\x74\x61\x62\0\x2e\x72\x65\x6c\x2e\x42\x54\x46\0\x4c\x42\x42\x30\x5f\x33\0\x4c\
\x42\x42\x30\x5f\x32\0\x62\x70\x66\x5f\x70\x72\x6f\x67\x31\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x5a\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x1b\x09\0\0\0\0\0\0\x8b\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\x39\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\xc8\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x35\0\0\0\x09\
\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x18\x08\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\
\x0c\0\0\0\x03\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x21\0\0\0\x01\0\0\0\
\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\x01\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x52\0\0\0\x01\0\0\0\x03\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x28\x01\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x6e\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\x2c\x01\0\0\0\0\0\0\x50\x05\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\x6a\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x38\x08\
\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\x0c\0\0\0\x07\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\
\0\0\0\0\x0b\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x7c\x06\0\0\0\0\0\
\0\xf0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x07\0\0\
\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x58\x08\0\0\0\0\0\0\xc0\0\0\0\0\
\0\0\0\x0c\0\0\0\x09\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x27\0\0\0\x03\
\x4c\xff\x6f\0\0\0\x80\0\0\0\0\0\0\0\0\0\0\0\0\x18\x09\0\0\0\0\0\0\x03\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x62\0\0\0\x02\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x70\x07\0\0\0\0\0\0\xa8\0\0\0\0\0\0\0\x01\0\0\0\
\x04\0\0\0\x08\0\0\0\0\0\0\0\x18\0\0\0\0\0\0\0";
}

#ifdef __cplusplus
struct example2_bpf *example2_bpf::open(const struct bpf_object_open_opts *opts) { return example2_bpf__open_opts(opts); }
struct example2_bpf *example2_bpf::open_and_load() { return example2_bpf__open_and_load(); }
int example2_bpf::load(struct example2_bpf *skel) { return example2_bpf__load(skel); }
int example2_bpf::attach(struct example2_bpf *skel) { return example2_bpf__attach(skel); }
void example2_bpf::detach(struct example2_bpf *skel) { example2_bpf__detach(skel); }
void example2_bpf::destroy(struct example2_bpf *skel) { example2_bpf__destroy(skel); }
const void *example2_bpf::elf_bytes(size_t *sz) { return example2_bpf__elf_bytes(sz); }
#endif /* __cplusplus */

__attribute__((unused)) static void
example2_bpf__assert(struct example2_bpf *s __attribute__((unused)))
{
#ifdef __cplusplus
#define _Static_assert static_assert
#endif
#ifdef __cplusplus
#undef _Static_assert
#endif
}

#endif /* __EXAMPLE2_BPF_SKEL_H__ */
